# Generated by Django 4.2.2 on 2023-06-22 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElevatorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevator_id', models.IntegerField()),
                ('current_floor', models.IntegerField(default=1)),
                ('is_door_open', models.BooleanField(default=True)),
                ('direction', models.CharField(choices=[('UP', 'UP'), ('DOWN', 'DOWN'), ('STANDING', 'STANDING')], default='STANDING', max_length=50)),
                ('is_operational', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'elevator',
                'ordering': ['elevator_id'],
            },
        ),
        migrations.CreateModel(
            name='ElevatorSystemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=100)),
                ('elevator_count', models.IntegerField(default=1)),
                ('floor_count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ElevatorRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_from_floor', models.IntegerField()),
                ('requested_to_floor', models.IntegerField()),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ElevatorSystem.elevatormodel')),
                ('elevator_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ElevatorSystem.elevatorsystemmodel')),
            ],
            options={
                'db_table': 'elevator_request',
                'ordering': ['elevator_id'],
            },
        ),
        migrations.AddField(
            model_name='elevatormodel',
            name='elevator_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ElevatorSystem.elevatorsystemmodel'),
        ),
    ]
